#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 9

/* Definitions for peripheral RGB_LED_1 */
#define XPAR_RGB_LED_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_RGB_LED_1_BASEADDR 0x40070000
#define XPAR_RGB_LED_1_HIGHADDR 0x4007ffff
#define XPAR_RGB_LED_1_INTERRUPT_PRESENT 0x0
#define XPAR_RGB_LED_1_IS_DUAL 0x0
#define XPAR_RGB_LED_1_GPIO_WIDTH 0x3

/* Canonical definitions for peripheral RGB_LED_1 */
#define XPAR_XGPIO_0_BASEADDR 0x40070000
#define XPAR_XGPIO_0_HIGHADDR 0x4007ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x3
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x0

/* Definitions for peripheral RGB_LED_2 */
#define XPAR_RGB_LED_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_RGB_LED_2_BASEADDR 0x40080000
#define XPAR_RGB_LED_2_HIGHADDR 0x4008ffff
#define XPAR_RGB_LED_2_INTERRUPT_PRESENT 0x0
#define XPAR_RGB_LED_2_IS_DUAL 0x0
#define XPAR_RGB_LED_2_GPIO_WIDTH 0x3

/* Canonical definitions for peripheral RGB_LED_2 */
#define XPAR_XGPIO_1_BASEADDR 0x40080000
#define XPAR_XGPIO_1_HIGHADDR 0x4008ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x3
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral SSD_ANODE1_BASE_1 */
#define XPAR_SSD_ANODE1_BASE_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_SSD_ANODE1_BASE_1_BASEADDR 0x40050000
#define XPAR_SSD_ANODE1_BASE_1_HIGHADDR 0x4005ffff
#define XPAR_SSD_ANODE1_BASE_1_INTERRUPT_PRESENT 0x0
#define XPAR_SSD_ANODE1_BASE_1_IS_DUAL 0x0
#define XPAR_SSD_ANODE1_BASE_1_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral SSD_ANODE1_BASE_1 */
#define XPAR_XGPIO_2_BASEADDR 0x40050000
#define XPAR_XGPIO_2_HIGHADDR 0x4005ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x4
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

/* Definitions for peripheral SSD_ANODE_BASE */
#define XPAR_SSD_ANODE_BASE_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_SSD_ANODE_BASE_BASEADDR 0x40030000
#define XPAR_SSD_ANODE_BASE_HIGHADDR 0x4003ffff
#define XPAR_SSD_ANODE_BASE_INTERRUPT_PRESENT 0x0
#define XPAR_SSD_ANODE_BASE_IS_DUAL 0x0
#define XPAR_SSD_ANODE_BASE_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral SSD_ANODE_BASE */
#define XPAR_XGPIO_3_BASEADDR 0x40030000
#define XPAR_XGPIO_3_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x4
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

/* Definitions for peripheral SSD_CATHOD1_BASE_1 */
#define XPAR_SSD_CATHOD1_BASE_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_SSD_CATHOD1_BASE_1_BASEADDR 0x40060000
#define XPAR_SSD_CATHOD1_BASE_1_HIGHADDR 0x4006ffff
#define XPAR_SSD_CATHOD1_BASE_1_INTERRUPT_PRESENT 0x0
#define XPAR_SSD_CATHOD1_BASE_1_IS_DUAL 0x0
#define XPAR_SSD_CATHOD1_BASE_1_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral SSD_CATHOD1_BASE_1 */
#define XPAR_XGPIO_4_BASEADDR 0x40060000
#define XPAR_XGPIO_4_HIGHADDR 0x4006ffff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x7
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_4_IS_DUAL 0x0

/* Definitions for peripheral SSD_CATHOD_BASE */
#define XPAR_SSD_CATHOD_BASE_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_SSD_CATHOD_BASE_BASEADDR 0x40040000
#define XPAR_SSD_CATHOD_BASE_HIGHADDR 0x4004ffff
#define XPAR_SSD_CATHOD_BASE_INTERRUPT_PRESENT 0x0
#define XPAR_SSD_CATHOD_BASE_IS_DUAL 0x0
#define XPAR_SSD_CATHOD_BASE_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral SSD_CATHOD_BASE */
#define XPAR_XGPIO_5_BASEADDR 0x40040000
#define XPAR_XGPIO_5_HIGHADDR 0x4004ffff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0x7
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_5_IS_DUAL 0x0

/* Definitions for peripheral BTN */
#define XPAR_BTN_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_BTN_BASEADDR 0x40020000
#define XPAR_BTN_HIGHADDR 0x4002ffff
#define XPAR_BTN_INTERRUPT_PRESENT 0x0
#define XPAR_BTN_IS_DUAL 0x0
#define XPAR_BTN_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral BTN */
#define XPAR_XGPIO_6_BASEADDR 0x40020000
#define XPAR_XGPIO_6_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_6_GPIO_WIDTH 0x4
#define XPAR_XGPIO_6_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_6_IS_DUAL 0x0

/* Definitions for peripheral LED */
#define XPAR_LED_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_LED_BASEADDR 0x40000000
#define XPAR_LED_HIGHADDR 0x4000ffff
#define XPAR_LED_INTERRUPT_PRESENT 0x0
#define XPAR_LED_IS_DUAL 0x0
#define XPAR_LED_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral LED */
#define XPAR_XGPIO_7_BASEADDR 0x40000000
#define XPAR_XGPIO_7_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_7_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_7_GPIO_WIDTH 0x10
#define XPAR_XGPIO_7_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_7_IS_DUAL 0x0

/* Definitions for peripheral SW */
#define XPAR_SW_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_SW_BASEADDR 0x40010000
#define XPAR_SW_HIGHADDR 0x4001ffff
#define XPAR_SW_INTERRUPT_PRESENT 0x0
#define XPAR_SW_IS_DUAL 0x0
#define XPAR_SW_GPIO_WIDTH 0xf

/* Canonical definitions for peripheral SW */
#define XPAR_XGPIO_8_BASEADDR 0x40010000
#define XPAR_XGPIO_8_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_8_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_8_GPIO_WIDTH 0xf
#define XPAR_XGPIO_8_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_8_IS_DUAL 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_KIND_OF_INTR 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_IVAR_RST_VAL 0x80000010
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_NUM_INTR_INPUTS 0x2
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_RISCV_0_AXI_INTC_HANDLER_TABLE 0x0

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x80000010
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x1
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x2
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 1

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_AXI_TIMER_0_BASEADDR 0x41c00000
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41c0ffff
#define XPAR_AXI_TIMER_0_CLOCK_FREQUENCY 0x4f790d5
#define XPAR_AXI_TIMER_0_INTERRUPTS 0x2001
#define XPAR_FABRIC_AXI_TIMER_0_INTR 1
#define XPAR_AXI_TIMER_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x41c00000
#define XPAR_FABRIC_XTMRCTR_0_INTR 1
#define XPAR_XTMRCTR_0_HIGHADDR 0x41c0ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY 0x4f790d5
#define XPAR_XTMRCTR_0_INTERRUPTS 0x2001
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0x41200001

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x0
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 0
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_0_INTR 0
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x0
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

#define XPAR_MIG_0_BASEADDRESS 0x80000000
#define XPAR_MIG_0_HIGHADDRESS 0x87ffffff

/*  CPU parameters definition */
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 83333333
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 1
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 4096
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0
#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_RISCV_D_LMB 0
#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define STDOUT_BASEADDRESS 0x40600000
#define STDIN_BASEADDRESS 0x40600000

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7s50"

#endif  /* end of protection macro */