domain_path: C:\Users\rojin\OneDrive\Desktop\projectTest\vitis_all\platform\export\platform\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
